name: ci-workflow
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome Step
        run: echo "Welcome To GitHub Actions"
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Repository Basic Info
        run: |
          echo "Repository Name: ${{github.repository}}"
          echo "Repository Owner: ${{github.repository_owner}}"
          echo "Runner OS: ${{runner.os}}"
          echo "Event Generated: ${{github.event_name}}"
          echo "_______List Of Branches________"
          git branch
          git log